/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

package billsoftware;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author liyan
 */
public class Sales extends javax.swing.JFrame {

    /**
     * Creates new form Sales
     */
    private final Databaseconfig dbConfig ;
    
    public Sales(Databaseconfig config) {
        this.dbConfig = config;
        initComponents();
        try {
            fetchInvoices();
            fetchSoldProducts();
        } catch (Exception ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void fetchInvoices()throws Exception{
    try{
            
            DefaultTableModel tblModel = (DefaultTableModel)table1.getModel();
            tblModel.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dbConfig.getUrl(),dbConfig.getUsername(),dbConfig.getPassword());
            Statement stmt = con.createStatement();
            String sql ="SELECT * FROM invoices";
            ResultSet rs = stmt.executeQuery(sql);
            
            while(rs.next()){
                
            String invoice_no = rs.getString("invoice_no");
            String customer_name = rs.getString("customer_name");
            String phone_number = rs.getString("phone_number");
            String date  = rs.getString("date");
            String time = rs.getString("time");
            String subtotal = rs.getString("subtotal");
            String discount = rs.getString("discount");
            String total = rs.getString("total");
            
            String tbData[] =  {invoice_no,customer_name,phone_number,date,time,subtotal,discount,total};
            tblModel.addRow(tbData);
            }
    
    }catch(Exception Ex){
    System.out.println(Ex);
    }
    
    }
    public void fetchSoldProducts()throws Exception {
        try{
        
            DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
            tblModel.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dbConfig.getUrl(),dbConfig.getUsername(),dbConfig.getPassword());
            Statement stmt = con.createStatement();
            String sql ="SELECT * FROM  invoice_items";
            ResultSet rs = stmt.executeQuery(sql);
        
            while(rs.next()){
             
            String item_id = rs.getString("item_id");
            String invoice_no = rs.getString("invoice_no");
            String product_name = rs.getString("product_name");
            String manufacturer = rs.getString("manufacturer");
            String model_no = rs.getString("model_no");
            String serial_no = rs.getString("serial_no");
            String unit_price = rs.getString("unit_price");
            String quantity = rs.getString("quantity");
            
            String tbData[] ={item_id,invoice_no,product_name,manufacturer,model_no,serial_no,unit_price,quantity};
            tblModel.addRow(tbData);
            }
        }catch(Exception ex){
        
            System.out.println(ex);
        
        }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        search = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnsearch = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1080, 768));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 211, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Items:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 480, 190, -1));

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "idem_id", "product name", "invoice No", "manufacturer", "model_no", "serial_no", "unit_price", "quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 1080, 220));

        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "InvoiceNo", "Customer Name", "phone no", "date", "time", "subtotal", "discount", "total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(table1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1080, 220));

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("View Sales And Items ");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 460, 60));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Invoice No:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 140, 30));

        search.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 250, 40));

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 30)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Invoices:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 190, 40));

        btnsearch.setBackground(new java.awt.Color(0, 51, 255));
        btnsearch.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 24)); // NOI18N
        btnsearch.setForeground(new java.awt.Color(0, 0, 0));
        btnsearch.setText("Search");
        btnsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsearchMouseClicked(evt);
            }
        });
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        jPanel1.add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 120, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8-back-52.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 770));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsearchMouseClicked
        // TODO add your handling code here:
        try{
            
            DefaultTableModel tblModel = (DefaultTableModel)table1.getModel();
            DefaultTableModel tblModel2 = (DefaultTableModel)table2.getModel();
            tblModel.setRowCount(0);
            tblModel2.setRowCount(0);
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = DriverManager.getConnection(dbConfig.getUrl(),dbConfig.getUsername(),dbConfig.getPassword());
            Statement stmt = con.createStatement();
            Statement stmt2 = con.createStatement();
            String sql1 ="SELECT * FROM  invoices WHERE invoice_no = '"+search.getText()+"'";
            String sql2 ="SELECT * FROM  invoice_items WHERE invoice_no = '"+search.getText()+"'";
            ResultSet rs  = stmt.executeQuery(sql1);
            ResultSet rs2 = stmt2.executeQuery(sql2);

             while(rs2.next()){
             
            String item_id = rs2.getString("item_id");
            String invoice_no = rs2.getString("invoice_no");
            String product_name = rs2.getString("product_name");
            String manufacturer = rs2.getString("manufacturer");
            String model_no = rs2.getString("model_no");
            String serial_no = rs2.getString("serial_no");
            String unit_price = rs2.getString("unit_price");
            String quantity = rs2.getString("quantity");
            
            String tbData2[] ={item_id,invoice_no,product_name,manufacturer,model_no,serial_no,unit_price,quantity};
            tblModel2.addRow(tbData2);
            }
             
             while(rs.next()){
                
            String invoice_no = rs.getString("invoice_no");
            String customer_name = rs.getString("customer_name");
            String phone_number = rs.getString("phone_number");
            String date  = rs.getString("date");
            String time = rs.getString("time");
            String subtotal = rs.getString("subtotal");
            String discount = rs.getString("discount");
            String total = rs.getString("total");
            
            String tbData[] =  {invoice_no,customer_name,phone_number,date,time,subtotal,discount,total};
            tblModel.addRow(tbData);
            }

        }catch(Exception e){
            System.out.println(e);

        };
    }//GEN-LAST:event_btnsearchMouseClicked

    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsearchActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
            AdminHome info = new AdminHome();
            info.setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                Databaseconfig config = new Databaseconfig();
                 new Sales(config).setVisible(true);
                }catch(Exception ex){
                }
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnsearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField search;
    private javax.swing.JTable table1;
    private javax.swing.JTable table2;
    // End of variables declaration//GEN-END:variables
}
