/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package billsoftware;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liyan
 */
public class UpdateProducts extends javax.swing.JFrame {

    /**
     * Creates new form UpdateProducts
     */
     private ProductDisplayService productdisplayservice;
    private final Databaseconfig dbConfig;
    public UpdateProducts(Databaseconfig config)throws IOException{
        initComponents();
         this.dbConfig = config;
         reCall();
    }
    private void reCall()throws IOException{
     productdisplayservice = new ProductDisplayService(dbConfig);
    try{
    DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
    productdisplayservice.showProducts(tblModel);
    
    }catch(SQLException ex){
     System.out.print(ex);
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table2 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        pname = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        pmanu = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        pmodelno = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pqty = new javax.swing.JTextField();
        pprice = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(176, 211, 209));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Product Id", "Product Name", "Manufacturer", "Model No", "Price", "Qty"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 1080, 220));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Products");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 170, 40));
        jPanel1.add(pname, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 160, 40));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Manufaturer");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 170, 40));

        id.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        id.setForeground(new java.awt.Color(0, 0, 0));
        id.setText("Product Id");
        jPanel1.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 170, 40));
        jPanel1.add(pmanu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 160, 160, 40));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setText("Model No");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 170, 40));
        jPanel1.add(pmodelno, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 160, 160, 40));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setText("Quantity");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 170, 40));
        jPanel1.add(pqty, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 160, 160, 40));
        jPanel1.add(pprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 160, 160, 40));

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("Price");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 160, 40));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Update or Delete products");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, 460, 60));

        update.setBackground(new java.awt.Color(189, 103, 219));
        update.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update Stock");
        update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateMouseClicked(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 140, 40));

        delete.setBackground(new java.awt.Color(189, 103, 219));
        delete.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        delete.setForeground(new java.awt.Color(255, 255, 255));
        delete.setText("Delete stock");
        delete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteMouseClicked(evt);
            }
        });
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        jPanel1.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, 140, 40));

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Product name");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 170, 40));

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("Product Id");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 170, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateMouseClicked
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
         Connection con = DriverManager.getConnection(dbConfig.getUrl(), dbConfig.getUsername(), dbConfig.getPassword());
         Statement stmt = con.createStatement();
         String sql = "UPDATE products SET productname = '"+pname.getText()+"', manufacturer = '"+pmanu.getText()+"', modelno = '"+pmodelno.getText()+"',price = '"+pprice.getText()+"',Qty='"+pqty.getText()+"' WHERE productid = '"+id.getText()+"'";
         int rs = stmt.executeUpdate(sql);
         if(rs > 0) {
                JOptionPane.showMessageDialog(this, "product updated successfully!");
            } else {
                JOptionPane.showMessageDialog(this, "Failed to update product.");
            }
        }catch(ClassNotFoundException | SQLException ex){
        
        System.out.println(ex);
        }finally{
        pname.setText("");
        pmanu.setText("");
        pmodelno.setText("");
        pprice.setText("");
        pqty.setText("");
        id.setText("");
            try {
                reCall();
            } catch (IOException ex) {
               System.out.println(ex);
            }
        
        }
        
    }//GEN-LAST:event_updateMouseClicked

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        // TODO add your handling code here:
        try{
        Class.forName("com.mysql.cj.jdbc.Driver");
        Connection con = DriverManager.getConnection(dbConfig.getUrl(),dbConfig.getUsername(),dbConfig.getPassword());
        Statement stmt = con.createStatement();
        String sql = "DELETE FROM products WHERE productid = '"+id.getText()+"'";
        int rs = stmt.executeUpdate(sql);
        if(rs > 0){
        JOptionPane.showMessageDialog(this, "Product Deleted Success");
        }else{
        JOptionPane.showMessageDialog(this, "Failled to delete product");
        }
        }catch(Exception ex){
        System.out.println(ex);
        }finally{
        pname.setText("");
        pmanu.setText("");
        pmodelno.setText("");
        pprice.setText("");
        pqty.setText("");
        id.setText("");
            try {
                reCall();
            } catch (IOException ex) {
               System.out.println(ex);
            }
        }
        
    }//GEN-LAST:event_deleteActionPerformed

    private void table2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table2MouseClicked
        // TODO add your handling code here:
        
         DefaultTableModel tblModel = (DefaultTableModel)table2.getModel();
         int selectedRowIndex = table2.getSelectedRow();
         id.setText(tblModel.getValueAt(selectedRowIndex, 0).toString());
         pname.setText(tblModel.getValueAt(selectedRowIndex, 1).toString());
         pmanu.setText(tblModel.getValueAt(selectedRowIndex, 2).toString());
         pmodelno.setText(tblModel.getValueAt(selectedRowIndex,3).toString());
         pprice.setText(tblModel.getValueAt(selectedRowIndex, 4).toString());
         pqty.setText(tblModel.getValueAt(selectedRowIndex, 5).toString());
    }//GEN-LAST:event_table2MouseClicked

    private void deleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // 
               try{
                 Databaseconfig config = new Databaseconfig();
                 new UpdateProducts(config).setVisible(true);
                }catch(IOException ex){
                System.out.println(ex);
                
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pmanu;
    private javax.swing.JTextField pmodelno;
    private javax.swing.JTextField pname;
    private javax.swing.JTextField pprice;
    private javax.swing.JTextField pqty;
    private javax.swing.JTable table2;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
